config/routes.rb
Rails.application.routes.draw do
  # get 'comments/index'

  # get 'comments/new'

  # get 'comments/edit'

  # get 'articles/index'

  # get 'articles/edit'
  
  # post 'articles/new'

  # get 'articles/show'

  post 'articles/asd'

  # ROUTE STANDARD

  # get 'articles/edit', to: "articles#edit", as: :articles
  # ------------------------------------------------------

  # RESTFULL ROUTE
  root :to => "articles#index" 
  resources :articles

  resources :comments
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
						length: { minimum: 5 }
	validates :content, presence: true,
						length: { minimum: 10 }
	validates :status, presence: true

	scope :status_active, -> {where(status: 'active')}
	default_scope {where(status: 'active')}

	#name relation must plural
	has_many :comments, dependent: :destroy

	# Article.create(title: "learn", content: "asd", status: "not active")
	# Article.last.comments.create([{content:"coment 1"},{content: "coment2"}])
end

app/models/comment.rb
class Comment < ApplicationRecord
	before_create :default_status
	belongs_to :articles, required: false
	# belongs_to :user
	# validates :content, presence: true, length: {minimum: 10}

	def default_status
		self.status = "not-active"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# layout "articles"
  # instanisasi class harus sesuai nama kelas {tapi harus sama : article}
  def index
    @article = Article.all
  end

  def new
    @article = Article.new
    @comment = Comment.new
  	
  end

   def edit
    @article = Article.find_by_id(params[:id])
  end

  def create
    @article = Article.new(params_artikel)
    if @article.save
    flash[:notice] = "Success Add Rows"
    redirect_to action: 'index'
  else
    flash[:notice] = "Error Add Rows"
    render 'new'
  end

  end

  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
  end

  def newreply
    @comment = Comment.new(params_comment)
    if @comment.save
      @comment = Article.find_by_id(params[:comment][:article_id])
      redirect_to action:'index'
    else
      render 'reply'
    end
  end

  def showReply
    @comment = Comment.find_by_id(params[:id])
  end



  def update
    @article = Article.find_by_id(params[:id])
    if @article.update(params_artikel)
      flash[:notice] = "Success Update Rows"
      redirect_to action: 'index'
    else
      flash[:notice] = "Error Update Rows"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])

    if @article.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to action: 'index'
    else
      flash[:error] = "fails delete a records"
      redirect_to action: 'index'
    end

  end

  def comment
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  private
   def params_artikel
    params.require(:article).permit(:title, :content, :status)
  end  

  def asd
      Article.create(title: "learn", content: "asd", status: "not active")
  Article.last.comments.create([{content:"coment 1"},{content: "coment2"}])
  end

  def list
  	  @artikel = Article.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

  def create
        @comment = Comment.new(params_comment)
      respond_to do |format|
        if @comment.save
          format.js {@comments = Article.find_by_id(params[:comment][:article_id])}
        else
          format.js {@article = Article.find_by_id(params[:comment][:article_id])}
        end
      end
    end

    private
    def params_comment
      params.require(:comment).permit(:article_id, :content)

    end

  #   def index
  # end

  # def new
  #   @comment = Comment.new
  # end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/articles.html.erb
<% content_for :list do %>
 This is the content for head
<% end %>

<h1>LIST</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
      <td></td>
    </tr>
  </thead>

  <tbody>
    <% @artikel.each do |article| %>
      <tr>
        <td><%= article.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/comment.html.erb
<h2><$= @article.title %></h2>
<p>@article.content</p>

<% for comment in @article.comments %>
<p> <%= comment.content %></p>



<%= start_form_tag (:action => "save_commnet", :id => @article) %>

<p><%= text_area("comment","content") %></p>
<p><input type="submit" name="submit" value="submit"></p>

<%= end_form_tag %>

app/views/articles/content.html.erb
<% content_for :main do %>
<p>HAIIi</p>
<% end %>
 <%= render "main" %>

app/views/articles/edit.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Edit Data Artikel</h5>
                <%= form_for @article do |f| %>
                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: 'form-control' %>
                 
                  
                </div>
                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  
                  
                </div>
                <div class="form-group">
                  <%= f.label :status %>
                  <%= f.radio_button :status, "active" %>
                  <%= label :artikel_status, 'active' %>
                  <%= f.radio_button :status, "non-active", :checked => true %>
                  <%= label :artikel_status, 'off' %>
                </div>
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

                <%= link_to 'back', articles_path, class: 'btn btn-md btn-info'%>
               
        </div>
      </div>
    </section>
  </div>
</div>






  

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      <!-- END OF CONTENT -->

					 <h2>Selamat Datang</h2>
				      <div class="jumbotron">
				      	<h1 class="display-4">Hello, world!</h1>
						<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
						<hr class="my-4">
						<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
						<p class="lead">
						<a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
						</p>
				      </div>

				      <!-- Data Artikel -->
				      <table class="table table-striped">
				      	<thead>
				      		<tr>
				      			<th>Title</th>
				      			<th>Content</th>
				      			<th>Status</th>
				      			<th>Action</th>
				      			<th>Reply</th>
				      			
				      		</tr>
				      	</thead>
				      	<tbody>
				      		<% @article.each do |article| %>
				      		<tr>
				      			<td><%= article.title %></td>
				      			<td><%= article.content.truncate(80) %></td>
				      			<td><%= article.status %></td>
				      			<td><%= link_to 'Read More', article_path(article.id) %>

				      				<%= link_to 'Edit', edit_article_path(article.id) %>
				      				<%= link_to 'Delete', article_path(article.id), method: "Delete", data: {confirm: 'Delete this data ? '} %>
				      				
				      			</td>
				      			<td><%= link_to 'Reply' %></td>
	   				       <% end %>
				      		</tr>
				      	</tbody>
				      </table>
				      
				      	
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

app/views/articles/new.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Tambah Data Artikel</h5>
                <%= form_for (@article) do |f| %>
                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: 'form-control' %>
                  <%= @article.errors[:title].first unless @article.errors[:title].blank? %>

                  
                </div>
                <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  <%= @article.errors[:content].first unless @article.errors[:content].blank? %>
                  
                </div>
                <div class="form-group">
                  <%= f.label :status %>
                  <%= f.radio_button :status, "active" %>
                  <%= label :artikel_status, 'active' %>
                  <%= f.radio_button :status, "non-active", :checked => true %>
                  <%= label :artikel_status, 'off' %>
                </div>
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

        </div>
      </div>
    </section>
  </div>
</div>






  

app/views/articles/reply.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
      <li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
      
    </ul>
</nav>
<div class="container">
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- CONTENT HERE -->
          <!-- END OF CONTENT -->

           <h2>Selamat Datang</h2>
           <h5>Tambah Data Artikel</h5>
                <%= form_for (@comment) do |f| %>
                  <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  
                </div>
  
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>

        </div>
      </div>
    </section>
  </div>
</div>






  

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>List Data</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item"><%= link_to 'Home', articles_path, class: 'btn btn-lg btn-primary' %></li>
			<li class="nav-item"><%= link_to 'Add Data', new_article_path, class: 'btn btn-lg btn-warning' %></li>
			
		</ul>
</nav>
<div class="container">
	<div class="content-wrapper">
		<section class="content">
			<div class="row">
				<div class="col-md-12">
					<!-- CONTENT HERE -->
				      <%= yield :list %>
				      
				      <!-- END OF CONTENT -->

					 <h3><%= @article.title %></h3>
					 <p><%= @article.content %></p>


					 <section class="section comments mb-5">
	<div class="">
		<h2 class="subtitle is-5"><strong><%= @article.comments.count %></strong> Comments</h2>
		<div id="list-comments">
			<%= render 'comments/comments'%>
		</div>
		<div class="comment-form">
			<hr />
			<h3 class="subtitle is-3">Leave a reply</h3>
			<div id="form-comment">
		 		<%= render 'comments/form' %>
			</div>
		</div>
	</div>
</section>

					 

					 <p><%= link_to 'back', articles_path, class: 'btn btn-md btn-info'%></p>
						
				     
				</div>
			</div>
		</section>
	</div>
</div>
	
  
</body>
</html>

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
	<p>
		
		<br/>
		<%= comment.content %>
	</p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for @comment, url: comments_path, remote: true  do |f| %>
	
	<%= f.hidden_field :article_id, value: @article.id %>
	
	<br />
	<%= f.label :content %>
	<%= f.text_area :content, cols: 20, rows: 10 , class: 'form-control'%>
	<br />
	<%= f.submit :submit , class: 'btn btn-primary' %>
<% end %>

app/views/comments/_reply.html.erb
                <%= form_for @comment do |f| %>
                  <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  
                </div>
  
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>







  

app/views/comments/create.js.erb
<% if @comment.errors.present? %>
$("#form-comment").html(" <%= j( render 'form' ) %>");
$($(".field_with_errors")[0]).append("<p class = 'message'> <%= escape_javascript( @comment.errors[:content].first ) %></p>");
<% else %>
$("#list-comments").html(" <%= j( render 'comments' ) %>");
$("#comment_content").val('');
$("div.field_with_errors p.message").remove();
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
                <%= form_for (@comment) do |f| %>
                  <div class="form-group">
                  <%= f.label :content %>
                  <%= f.text_area :content, cols: 20, rows: 10, class: 'form-control' %>
                  
                </div>
  
                <div class="form-group">
                    <%= f.submit :submit %>
                </div>
                <% end %>







  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Latihan</title>
    <%= csrf_meta_tags %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= yield %>

  </body>
</html>